# Generated by Django 3.0.4 on 2020-04-05 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_products', '0005_auto_20200401_1947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=500, null=True, verbose_name='slug')),
                ('year_founded', models.IntegerField(null=True, verbose_name='Year founded')),
                ('mission', models.TextField(max_length=5000, null=True, verbose_name='Mission')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 1')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=125, null=True, verbose_name='Website')),
                ('street', models.CharField(blank=True, max_length=250, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=125, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=125, null=True, verbose_name='Province')),
                ('country', models.CharField(blank=True, max_length=125, null=True, verbose_name='Country')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='Zip Code')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('is_organization', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('founder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='founder')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigner_logos', to=settings.FILER_IMAGE_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Fundraiser',
                'verbose_name_plural': 'Fundraisers',
            },
        ),
        migrations.CreateModel(
            name='FundraiserTransaction',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('flow', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3, verbose_name='Flow')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Amount')),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Old Balance')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='django_fundraisers.Fundraiser', verbose_name='Fundraiser')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_fundraisers.fundraisertransaction_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_products.Product')),
                ('seo_title', models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title')),
                ('seo_description', models.TextField(blank=True, verbose_name='seo description')),
                ('live', models.BooleanField(default=True, verbose_name='live')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('latest_revision_created_at', models.DateTimeField(editable=False, null=True, verbose_name='latest revision created at')),
                ('min_donation', models.DecimalField(decimal_places=0, default=10000, help_text='Minimum donation needed for this campaign', max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='min donation')),
                ('target_donation', models.DecimalField(decimal_places=0, default=10000, help_text='Donation needed for this campaign', max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='target donation')),
                ('summary', models.TextField(help_text='Describe campaign shortly', max_length=250, verbose_name='summary')),
                ('body', models.TextField(help_text='Describe campaign more verbose', max_length=5000, verbose_name='body')),
                ('fundraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='django_fundraisers.Fundraiser', verbose_name='fundraiser')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
            bases=('django_products.product', models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='is deleted?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_active', models.BooleanField(default=False, editable=False, verbose_name='is active?')),
                ('is_admin', models.BooleanField(default=False, editable=False, verbose_name='is admin?')),
                ('is_staff', models.BooleanField(default=False, editable=False, verbose_name='is staff?')),
                ('is_follower', models.BooleanField(default=True, editable=False, verbose_name='is follower?')),
                ('date_joined', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date joined')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter')),
                ('fundraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='django_fundraisers.Fundraiser', verbose_name='fundraiser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'unique_together': {('fundraiser', 'member')},
            },
        ),
    ]
